/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Errors, ErrorsInterface } from "../Errors";

const _abi = [
  {
    type: "error",
    name: "ALREADY_INITIALIZED",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "APR_GREATER_THAN_MAX_APR",
    inputs: [
      {
        name: "apr",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxAPR",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "APR_LOWER_THAN_MIN_APR",
    inputs: [
      {
        name: "apr",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minAPR",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ARRAY_LENGTHS_MISMATCH",
    inputs: [],
  },
  {
    type: "error",
    name: "BORROWER_IS_NOT_LENDER",
    inputs: [
      {
        name: "borrower",
        type: "address",
        internalType: "address",
      },
      {
        name: "lender",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "BORROW_TOKEN_INCREASE_EXCEEDS_DEBT_TOKEN_DECREASE",
    inputs: [
      {
        name: "borrowTokenIncrease",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "debtTokenDecrease",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "COMPENSATOR_IS_NOT_BORROWER",
    inputs: [
      {
        name: "compensator",
        type: "address",
        internalType: "address",
      },
      {
        name: "borrower",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "CREDIT_LOWER_THAN_MINIMUM_CREDIT",
    inputs: [
      {
        name: "credit",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minimumCreditBorrowToken",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "CREDIT_LOWER_THAN_MINIMUM_CREDIT_OPENING",
    inputs: [
      {
        name: "credit",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minimumCreditBorrowToken",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "CREDIT_NOT_FOR_SALE",
    inputs: [
      {
        name: "creditPositionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "CREDIT_POSITION_ALREADY_CLAIMED",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "CREDIT_POSITION_NOT_TRANSFERRABLE",
    inputs: [
      {
        name: "creditPositionId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "loanStatus",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "borrowerCR",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "CR_BELOW_OPENING_LIMIT_BORROW_CR",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "cr",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "riskCollateralRatio",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "DEBT_TOKEN_CAP_EXCEEDED",
    inputs: [
      {
        name: "debtTokenCap",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "actual",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "DUE_DATE_NOT_COMPATIBLE",
    inputs: [
      {
        name: "dueDate1",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "dueDate2",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "GRACE_PERIOD_NOT_OVER",
    inputs: [],
  },
  {
    type: "error",
    name: "INVALID_ACTION",
    inputs: [
      {
        name: "action",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_ACTIONS_BITMAP",
    inputs: [
      {
        name: "actionsBitmap",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_ADAPTER",
    inputs: [
      {
        name: "adapter",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_ADDRESS",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_AMOUNT",
    inputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_APR_RANGE",
    inputs: [
      {
        name: "minAPR",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxAPR",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_AVERAGE_BLOCK_TIME",
    inputs: [],
  },
  {
    type: "error",
    name: "INVALID_BORROWER",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_BORROW_OFFER",
    inputs: [
      {
        name: "borrower",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_COLLATERAL_PERCENTAGE_PREMIUM",
    inputs: [
      {
        name: "percentage",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_COLLATERAL_RATIO",
    inputs: [
      {
        name: "cr",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_CREDIT_POSITION_ID",
    inputs: [
      {
        name: "creditPositionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_DEBT_POSITION_ID",
    inputs: [
      {
        name: "debtPositionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_DECIMALS",
    inputs: [
      {
        name: "decimals",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_KEY",
    inputs: [
      {
        name: "key",
        type: "string",
        internalType: "string",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_LENDER",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_LIQUIDATION_COLLATERAL_RATIO",
    inputs: [
      {
        name: "crOpening",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "crLiquidation",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_LOAN_OFFER",
    inputs: [
      {
        name: "lender",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_MARKET",
    inputs: [
      {
        name: "market",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_MATURITY",
    inputs: [
      {
        name: "maturity",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_MAXIMUM_MATURITY",
    inputs: [
      {
        name: "maxMaturity",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_MSG_VALUE",
    inputs: [
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_OFFER",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_OFFER_CONFIGS",
    inputs: [
      {
        name: "minTenorBorrowOffer",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxTenorBorrowOffer",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minAPRBorrowOffer",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxAPRBorrowOffer",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minTenorLoanOffer",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxTenorLoanOffer",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minAPRLoanOffer",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxAPRLoanOffer",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_POSITION_ID",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_PRICE",
    inputs: [
      {
        name: "aggregator",
        type: "address",
        internalType: "address",
      },
      {
        name: "price",
        type: "int256",
        internalType: "int256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_STALE_PRICE_INTERVAL",
    inputs: [
      {
        name: "a",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "b",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_TENOR_RANGE",
    inputs: [
      {
        name: "minTenor",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxTenor",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_TOKEN",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "INVALID_TWAP_WINDOW",
    inputs: [],
  },
  {
    type: "error",
    name: "INVALID_VAULT",
    inputs: [
      {
        name: "vault",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "INVERTED_OFFERS",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "maturity",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "LIQUIDATE_PROFIT_BELOW_MINIMUM_COLLATERAL_PROFIT",
    inputs: [
      {
        name: "liquidatorProfitCollateralToken",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minimumCollateralProfit",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "LIQUIDATOR_IS_NOT_LENDER",
    inputs: [
      {
        name: "liquidator",
        type: "address",
        internalType: "address",
      },
      {
        name: "lender",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "LOAN_ALREADY_REPAID",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "LOAN_NOT_ACTIVE",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "LOAN_NOT_LIQUIDATABLE",
    inputs: [
      {
        name: "debtPositionId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "cr",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "loanStatus",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "LOAN_NOT_REPAID",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "LOAN_NOT_SELF_LIQUIDATABLE",
    inputs: [
      {
        name: "creditPositionId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "cr",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "loanStatus",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "MATURITIES_NOT_STRICTLY_INCREASING",
    inputs: [],
  },
  {
    type: "error",
    name: "MATURITY_OUT_OF_RANGE",
    inputs: [
      {
        name: "maturity",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minTenor",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxTenor",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "MUST_IMPROVE_COLLATERAL_RATIO",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "crBefore",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "crAfter",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "NOT_ENOUGH_BORROW_ATOKEN_BALANCE",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "balance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "NOT_ENOUGH_CASH",
    inputs: [
      {
        name: "cash",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "NOT_ENOUGH_CREDIT",
    inputs: [
      {
        name: "credit",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "NOT_SUPPORTED",
    inputs: [],
  },
  {
    type: "error",
    name: "NULL_ADDRESS",
    inputs: [],
  },
  {
    type: "error",
    name: "NULL_AMOUNT",
    inputs: [],
  },
  {
    type: "error",
    name: "NULL_ARRAY",
    inputs: [],
  },
  {
    type: "error",
    name: "NULL_MATURITY",
    inputs: [],
  },
  {
    type: "error",
    name: "NULL_OFFER",
    inputs: [],
  },
  {
    type: "error",
    name: "NULL_STALE_PRICE",
    inputs: [],
  },
  {
    type: "error",
    name: "PAST_DEADLINE",
    inputs: [
      {
        name: "deadline",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "PAST_MATURITY",
    inputs: [
      {
        name: "maturity",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "PAUSED_MARKET",
    inputs: [
      {
        name: "market",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "REINITIALIZE_ALL_CLAIMS_PRESERVED",
    inputs: [
      {
        name: "newScaledTotalSupplyAfter",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "newScaledTotalSupplyBefore",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "oldScaledTotalSupply",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "REINITIALIZE_INSOLVENT",
    inputs: [
      {
        name: "newTotalSupplyAfter",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "newTotalSupplyBefore",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "aTokenBalance",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "REINITIALIZE_MIGRATION_EXPECTED_IN_ONE_TRANSACTION",
    inputs: [
      {
        name: "totalSupply",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "REINITIALIZE_PER_USER_CHECK",
    inputs: [
      {
        name: "expected",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "actual",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "REINITIALIZE_PER_USER_CHECK_DELTA",
    inputs: [
      {
        name: "expected",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "actual",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "SEQUENCER_DOWN",
    inputs: [],
  },
  {
    type: "error",
    name: "STALE_PRICE",
    inputs: [
      {
        name: "aggregator",
        type: "address",
        internalType: "address",
      },
      {
        name: "updatedAt",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "UNAUTHORIZED",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "UNAUTHORIZED_ACTION",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "onBehalfOf",
        type: "address",
        internalType: "address",
      },
      {
        name: "action",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "VALUE_GREATER_THAN_MAX",
    inputs: [
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "max",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212200af1a08dffc8a768f26ccbcb451e59174412b8f73757f4a74be531b61e5a1b0364736f6c63430008170033";

type ErrorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ErrorsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Errors__factory extends ContractFactory {
  constructor(...args: ErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(overrides?: Overrides & { from?: string }): Promise<Errors> {
    return super.deploy(overrides || {}) as Promise<Errors>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Errors {
    return super.attach(address) as Errors;
  }
  override connect(signer: Signer): Errors__factory {
    return super.connect(signer) as Errors__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ErrorsInterface {
    return new utils.Interface(_abi) as ErrorsInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Errors {
    return new Contract(address, _abi, signerOrProvider) as Errors;
  }
}
