/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type InitializeFeeConfigParamsStruct = {
  swapFeeAPR: BigNumberish;
  fragmentationFee: BigNumberish;
  liquidationRewardPercent: BigNumberish;
  overdueCollateralProtocolPercent: BigNumberish;
  collateralProtocolPercent: BigNumberish;
  feeRecipient: string;
};

export type InitializeFeeConfigParamsStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string
] & {
  swapFeeAPR: BigNumber;
  fragmentationFee: BigNumber;
  liquidationRewardPercent: BigNumber;
  overdueCollateralProtocolPercent: BigNumber;
  collateralProtocolPercent: BigNumber;
  feeRecipient: string;
};

export type InitializeRiskConfigParamsStruct = {
  crOpening: BigNumberish;
  crLiquidation: BigNumberish;
  minimumCreditBorrowToken: BigNumberish;
  minTenor: BigNumberish;
  maxTenor: BigNumberish;
  maturities: BigNumberish[];
};

export type InitializeRiskConfigParamsStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber[]
] & {
  crOpening: BigNumber;
  crLiquidation: BigNumber;
  minimumCreditBorrowToken: BigNumber;
  minTenor: BigNumber;
  maxTenor: BigNumber;
  maturities: BigNumber[];
};

export type InitializeOracleParamsStruct = { priceFeed: string };

export type InitializeOracleParamsStructOutput = [string] & {
  priceFeed: string;
};

export type InitializeDataParamsStruct = {
  weth: string;
  underlyingCollateralToken: string;
  underlyingBorrowToken: string;
  variablePool: string;
  borrowTokenVault: string;
  sizeFactory: string;
};

export type InitializeDataParamsStructOutput = [
  string,
  string,
  string,
  string,
  string,
  string
] & {
  weth: string;
  underlyingCollateralToken: string;
  underlyingBorrowToken: string;
  variablePool: string;
  borrowTokenVault: string;
  sizeFactory: string;
};

export type PriceFeedParamsStruct = {
  uniswapV3Pool: string;
  twapWindow: BigNumberish;
  averageBlockTime: BigNumberish;
  baseToken: string;
  quoteToken: string;
  baseAggregator: string;
  quoteAggregator: string;
  baseStalePriceInterval: BigNumberish;
  quoteStalePriceInterval: BigNumberish;
  sequencerUptimeFeed: string;
};

export type PriceFeedParamsStructOutput = [
  string,
  number,
  number,
  string,
  string,
  string,
  string,
  BigNumber,
  BigNumber,
  string
] & {
  uniswapV3Pool: string;
  twapWindow: number;
  averageBlockTime: number;
  baseToken: string;
  quoteToken: string;
  baseAggregator: string;
  quoteAggregator: string;
  baseStalePriceInterval: BigNumber;
  quoteStalePriceInterval: BigNumber;
  sequencerUptimeFeed: string;
};

export type CopyLimitOrderConfigStruct = {
  minTenor: BigNumberish;
  maxTenor: BigNumberish;
  minAPR: BigNumberish;
  maxAPR: BigNumberish;
  offsetAPR: BigNumberish;
};

export type CopyLimitOrderConfigStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  minTenor: BigNumber;
  maxTenor: BigNumber;
  minAPR: BigNumber;
  maxAPR: BigNumber;
  offsetAPR: BigNumber;
};

export interface SizeFactoryInterface extends utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "UPGRADE_INTERFACE_VERSION()": FunctionFragment;
    "authorizationNonces(address)": FunctionFragment;
    "authorizations(uint256,address,address)": FunctionFragment;
    "callMarket(address,bytes)": FunctionFragment;
    "collectionsManager()": FunctionFragment;
    "createBorrowTokenVault(address,address)": FunctionFragment;
    "createMarket((uint256,uint256,uint256,uint256,uint256,address),(uint256,uint256,uint256,uint256,uint256,uint256[]),(address),(address,address,address,address,address,address))": FunctionFragment;
    "createPriceFeed((address,uint32,uint32,address,address,address,address,uint256,uint256,address))": FunctionFragment;
    "getBorrowOfferAPR(address,uint256,address,address,uint256)": FunctionFragment;
    "getLoanOfferAPR(address,uint256,address,address,uint256)": FunctionFragment;
    "getMarket(uint256)": FunctionFragment;
    "getMarketDescriptions()": FunctionFragment;
    "getMarkets()": FunctionFragment;
    "getMarketsCount()": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "isAuthorized(address,address,uint8)": FunctionFragment;
    "isAuthorizedAll(address,address,uint256)": FunctionFragment;
    "isBorrowAPRLowerThanLoanOfferAPRs(address,uint256,address,uint256)": FunctionFragment;
    "isLoanAPRGreaterThanBorrowOfferAPRs(address,uint256,address,uint256)": FunctionFragment;
    "isMarket(address)": FunctionFragment;
    "multicall(bytes[])": FunctionFragment;
    "nonTransferrableTokenVaultImplementation()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "removeMarket(address)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeAllAuthorizations()": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setAuthorization(address,uint256)": FunctionFragment;
    "setCollectionsManager(address)": FunctionFragment;
    "setNonTransferrableRebasingTokenVaultImplementation(address)": FunctionFragment;
    "setSizeImplementation(address)": FunctionFragment;
    "setUserCollectionCopyLimitOrderConfigs(uint256,(uint256,uint256,uint256,uint256,int256),(uint256,uint256,uint256,uint256,int256))": FunctionFragment;
    "setUserCollectionCopyLimitOrderConfigsOnBehalfOf(uint256,(uint256,uint256,uint256,uint256,int256),(uint256,uint256,uint256,uint256,int256),address)": FunctionFragment;
    "sizeImplementation()": FunctionFragment;
    "subscribeToCollections(uint256[])": FunctionFragment;
    "subscribeToCollectionsOnBehalfOf(uint256[],address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "unsubscribeFromCollections(uint256[])": FunctionFragment;
    "unsubscribeFromCollectionsOnBehalfOf(uint256[],address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_ADMIN_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "authorizationNonces"
      | "authorizations"
      | "callMarket"
      | "collectionsManager"
      | "createBorrowTokenVault"
      | "createMarket"
      | "createPriceFeed"
      | "getBorrowOfferAPR"
      | "getLoanOfferAPR"
      | "getMarket"
      | "getMarketDescriptions"
      | "getMarkets"
      | "getMarketsCount"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isAuthorized"
      | "isAuthorizedAll"
      | "isBorrowAPRLowerThanLoanOfferAPRs"
      | "isLoanAPRGreaterThanBorrowOfferAPRs"
      | "isMarket"
      | "multicall"
      | "nonTransferrableTokenVaultImplementation"
      | "proxiableUUID"
      | "removeMarket"
      | "renounceRole"
      | "revokeAllAuthorizations"
      | "revokeRole"
      | "setAuthorization"
      | "setCollectionsManager"
      | "setNonTransferrableRebasingTokenVaultImplementation"
      | "setSizeImplementation"
      | "setUserCollectionCopyLimitOrderConfigs"
      | "setUserCollectionCopyLimitOrderConfigsOnBehalfOf"
      | "sizeImplementation"
      | "subscribeToCollections"
      | "subscribeToCollectionsOnBehalfOf"
      | "supportsInterface"
      | "unsubscribeFromCollections"
      | "unsubscribeFromCollectionsOnBehalfOf"
      | "upgradeToAndCall"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizationNonces",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizations",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "callMarket",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collectionsManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createBorrowTokenVault",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [
      InitializeFeeConfigParamsStruct,
      InitializeRiskConfigParamsStruct,
      InitializeOracleParamsStruct,
      InitializeDataParamsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createPriceFeed",
    values: [PriceFeedParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowOfferAPR",
    values: [string, BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanOfferAPR",
    values: [string, BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketDescriptions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedAll",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isBorrowAPRLowerThanLoanOfferAPRs",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isLoanAPRGreaterThanBorrowOfferAPRs",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isMarket", values: [string]): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "nonTransferrableTokenVaultImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeMarket",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAllAuthorizations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorization",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCollectionsManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setNonTransferrableRebasingTokenVaultImplementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSizeImplementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserCollectionCopyLimitOrderConfigs",
    values: [
      BigNumberish,
      CopyLimitOrderConfigStruct,
      CopyLimitOrderConfigStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserCollectionCopyLimitOrderConfigsOnBehalfOf",
    values: [
      BigNumberish,
      CopyLimitOrderConfigStruct,
      CopyLimitOrderConfigStruct,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sizeImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeToCollections",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeToCollectionsOnBehalfOf",
    values: [BigNumberish[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsubscribeFromCollections",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "unsubscribeFromCollectionsOnBehalfOf",
    values: [BigNumberish[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizationNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "callMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectionsManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBorrowTokenVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowOfferAPR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanOfferAPR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketDescriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarkets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBorrowAPRLowerThanLoanOfferAPRs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isLoanAPRGreaterThanBorrowOfferAPRs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nonTransferrableTokenVaultImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAllAuthorizations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCollectionsManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNonTransferrableRebasingTokenVaultImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSizeImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserCollectionCopyLimitOrderConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserCollectionCopyLimitOrderConfigsOnBehalfOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sizeImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribeToCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribeToCollectionsOnBehalfOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsubscribeFromCollections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsubscribeFromCollectionsOnBehalfOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "CollectionsManagerSet(address,address)": EventFragment;
    "CreateBorrowTokenVault(address)": EventFragment;
    "CreateMarket(address)": EventFragment;
    "CreatePriceFeed(address)": EventFragment;
    "Initialized(uint64)": EventFragment;
    "NonTransferrableRebasingTokenVaultImplementationSet(address,address)": EventFragment;
    "RemoveMarket(address)": EventFragment;
    "RevokeAllAuthorizations(address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "SetAuthorization(address,address,uint256,uint256)": EventFragment;
    "SizeImplementationSet(address,address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CollectionsManagerSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateBorrowTokenVault"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateMarket"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreatePriceFeed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NonTransferrableRebasingTokenVaultImplementationSet"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveMarket"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevokeAllAuthorizations"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetAuthorization"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SizeImplementationSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface CollectionsManagerSetEventObject {
  oldCollectionsManager: string;
  newCollectionsManager: string;
}
export type CollectionsManagerSetEvent = TypedEvent<
  [string, string],
  CollectionsManagerSetEventObject
>;

export type CollectionsManagerSetEventFilter =
  TypedEventFilter<CollectionsManagerSetEvent>;

export interface CreateBorrowTokenVaultEventObject {
  borrowTokenVault: string;
}
export type CreateBorrowTokenVaultEvent = TypedEvent<
  [string],
  CreateBorrowTokenVaultEventObject
>;

export type CreateBorrowTokenVaultEventFilter =
  TypedEventFilter<CreateBorrowTokenVaultEvent>;

export interface CreateMarketEventObject {
  market: string;
}
export type CreateMarketEvent = TypedEvent<[string], CreateMarketEventObject>;

export type CreateMarketEventFilter = TypedEventFilter<CreateMarketEvent>;

export interface CreatePriceFeedEventObject {
  priceFeed: string;
}
export type CreatePriceFeedEvent = TypedEvent<
  [string],
  CreatePriceFeedEventObject
>;

export type CreatePriceFeedEventFilter = TypedEventFilter<CreatePriceFeedEvent>;

export interface InitializedEventObject {
  version: BigNumber;
}
export type InitializedEvent = TypedEvent<[BigNumber], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface NonTransferrableRebasingTokenVaultImplementationSetEventObject {
  oldNonTransferrableRebasingTokenVaultImplementation: string;
  newNonTransferrableRebasingTokenVaultImplementation: string;
}
export type NonTransferrableRebasingTokenVaultImplementationSetEvent =
  TypedEvent<
    [string, string],
    NonTransferrableRebasingTokenVaultImplementationSetEventObject
  >;

export type NonTransferrableRebasingTokenVaultImplementationSetEventFilter =
  TypedEventFilter<NonTransferrableRebasingTokenVaultImplementationSetEvent>;

export interface RemoveMarketEventObject {
  market: string;
}
export type RemoveMarketEvent = TypedEvent<[string], RemoveMarketEventObject>;

export type RemoveMarketEventFilter = TypedEventFilter<RemoveMarketEvent>;

export interface RevokeAllAuthorizationsEventObject {
  sender: string;
}
export type RevokeAllAuthorizationsEvent = TypedEvent<
  [string],
  RevokeAllAuthorizationsEventObject
>;

export type RevokeAllAuthorizationsEventFilter =
  TypedEventFilter<RevokeAllAuthorizationsEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface SetAuthorizationEventObject {
  sender: string;
  operator: string;
  actionsBitmap: BigNumber;
  nonce: BigNumber;
}
export type SetAuthorizationEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  SetAuthorizationEventObject
>;

export type SetAuthorizationEventFilter =
  TypedEventFilter<SetAuthorizationEvent>;

export interface SizeImplementationSetEventObject {
  oldSizeImplementation: string;
  newSizeImplementation: string;
}
export type SizeImplementationSetEvent = TypedEvent<
  [string, string],
  SizeImplementationSetEventObject
>;

export type SizeImplementationSetEventFilter =
  TypedEventFilter<SizeImplementationSetEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface SizeFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SizeFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<[string]>;

    authorizationNonces(
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { nonce: BigNumber }>;

    authorizations(
      nonce: BigNumberish,
      operator: string,
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { authorizedActionsBitmap: BigNumber }>;

    callMarket(
      market: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    collectionsManager(overrides?: CallOverrides): Promise<[string]>;

    createBorrowTokenVault(
      variablePool: string,
      underlyingBorrowToken: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    createMarket(
      feeConfigParams: InitializeFeeConfigParamsStruct,
      riskConfigParams: InitializeRiskConfigParamsStruct,
      oracleParams: InitializeOracleParamsStruct,
      dataParams: InitializeDataParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    createPriceFeed(
      _priceFeedParams: PriceFeedParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getBorrowOfferAPR(
      user: string,
      collectionId: BigNumberish,
      market: string,
      rateProvider: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLoanOfferAPR(
      user: string,
      collectionId: BigNumberish,
      market: string,
      rateProvider: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMarket(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMarketDescriptions(
      overrides?: CallOverrides
    ): Promise<[string[]] & { descriptions: string[] }>;

    getMarkets(
      overrides?: CallOverrides
    ): Promise<[string[]] & { _markets: string[] }>;

    getMarketsCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      _owner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isAuthorized(
      operator: string,
      onBehalfOf: string,
      action: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isAuthorizedAll(
      operator: string,
      onBehalfOf: string,
      actionsBitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isBorrowAPRLowerThanLoanOfferAPRs(
      user: string,
      borrowAPR: BigNumberish,
      market: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isLoanAPRGreaterThanBorrowOfferAPRs(
      user: string,
      loanAPR: BigNumberish,
      market: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isMarket(candidate: string, overrides?: CallOverrides): Promise<[boolean]>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    nonTransferrableTokenVaultImplementation(
      overrides?: CallOverrides
    ): Promise<[string]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    removeMarket(
      market: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    revokeAllAuthorizations(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setAuthorization(
      operator: string,
      actionsBitmap: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setCollectionsManager(
      _collectionsManager: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setNonTransferrableRebasingTokenVaultImplementation(
      _nonTransferrableTokenVaultImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setSizeImplementation(
      _sizeImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setUserCollectionCopyLimitOrderConfigs(
      collectionId: BigNumberish,
      copyLoanOfferConfig: CopyLimitOrderConfigStruct,
      copyBorrowOfferConfig: CopyLimitOrderConfigStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setUserCollectionCopyLimitOrderConfigsOnBehalfOf(
      collectionId: BigNumberish,
      copyLoanOfferConfig: CopyLimitOrderConfigStruct,
      copyBorrowOfferConfig: CopyLimitOrderConfigStruct,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    sizeImplementation(overrides?: CallOverrides): Promise<[string]>;

    subscribeToCollections(
      collectionIds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    subscribeToCollectionsOnBehalfOf(
      collectionIds: BigNumberish[],
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    unsubscribeFromCollections(
      collectionIds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    unsubscribeFromCollectionsOnBehalfOf(
      collectionIds: BigNumberish[],
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[string]>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

  authorizationNonces(
    onBehalfOf: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  authorizations(
    nonce: BigNumberish,
    operator: string,
    onBehalfOf: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callMarket(
    market: string,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  collectionsManager(overrides?: CallOverrides): Promise<string>;

  createBorrowTokenVault(
    variablePool: string,
    underlyingBorrowToken: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  createMarket(
    feeConfigParams: InitializeFeeConfigParamsStruct,
    riskConfigParams: InitializeRiskConfigParamsStruct,
    oracleParams: InitializeOracleParamsStruct,
    dataParams: InitializeDataParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  createPriceFeed(
    _priceFeedParams: PriceFeedParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getBorrowOfferAPR(
    user: string,
    collectionId: BigNumberish,
    market: string,
    rateProvider: string,
    maturity: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLoanOfferAPR(
    user: string,
    collectionId: BigNumberish,
    market: string,
    rateProvider: string,
    maturity: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMarket(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getMarketDescriptions(overrides?: CallOverrides): Promise<string[]>;

  getMarkets(overrides?: CallOverrides): Promise<string[]>;

  getMarketsCount(overrides?: CallOverrides): Promise<BigNumber>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    _owner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isAuthorized(
    operator: string,
    onBehalfOf: string,
    action: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isAuthorizedAll(
    operator: string,
    onBehalfOf: string,
    actionsBitmap: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isBorrowAPRLowerThanLoanOfferAPRs(
    user: string,
    borrowAPR: BigNumberish,
    market: string,
    maturity: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isLoanAPRGreaterThanBorrowOfferAPRs(
    user: string,
    loanAPR: BigNumberish,
    market: string,
    maturity: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isMarket(candidate: string, overrides?: CallOverrides): Promise<boolean>;

  multicall(
    data: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  nonTransferrableTokenVaultImplementation(
    overrides?: CallOverrides
  ): Promise<string>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  removeMarket(
    market: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    callerConfirmation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  revokeAllAuthorizations(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setAuthorization(
    operator: string,
    actionsBitmap: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setCollectionsManager(
    _collectionsManager: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setNonTransferrableRebasingTokenVaultImplementation(
    _nonTransferrableTokenVaultImplementation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setSizeImplementation(
    _sizeImplementation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setUserCollectionCopyLimitOrderConfigs(
    collectionId: BigNumberish,
    copyLoanOfferConfig: CopyLimitOrderConfigStruct,
    copyBorrowOfferConfig: CopyLimitOrderConfigStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setUserCollectionCopyLimitOrderConfigsOnBehalfOf(
    collectionId: BigNumberish,
    copyLoanOfferConfig: CopyLimitOrderConfigStruct,
    copyBorrowOfferConfig: CopyLimitOrderConfigStruct,
    onBehalfOf: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  sizeImplementation(overrides?: CallOverrides): Promise<string>;

  subscribeToCollections(
    collectionIds: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  subscribeToCollectionsOnBehalfOf(
    collectionIds: BigNumberish[],
    onBehalfOf: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  unsubscribeFromCollections(
    collectionIds: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  unsubscribeFromCollectionsOnBehalfOf(
    collectionIds: BigNumberish[],
    onBehalfOf: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

    authorizationNonces(
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    authorizations(
      nonce: BigNumberish,
      operator: string,
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    callMarket(
      market: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    collectionsManager(overrides?: CallOverrides): Promise<string>;

    createBorrowTokenVault(
      variablePool: string,
      underlyingBorrowToken: string,
      overrides?: CallOverrides
    ): Promise<string>;

    createMarket(
      feeConfigParams: InitializeFeeConfigParamsStruct,
      riskConfigParams: InitializeRiskConfigParamsStruct,
      oracleParams: InitializeOracleParamsStruct,
      dataParams: InitializeDataParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    createPriceFeed(
      _priceFeedParams: PriceFeedParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    getBorrowOfferAPR(
      user: string,
      collectionId: BigNumberish,
      market: string,
      rateProvider: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLoanOfferAPR(
      user: string,
      collectionId: BigNumberish,
      market: string,
      rateProvider: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarket(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

    getMarketDescriptions(overrides?: CallOverrides): Promise<string[]>;

    getMarkets(overrides?: CallOverrides): Promise<string[]>;

    getMarketsCount(overrides?: CallOverrides): Promise<BigNumber>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(_owner: string, overrides?: CallOverrides): Promise<void>;

    isAuthorized(
      operator: string,
      onBehalfOf: string,
      action: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isAuthorizedAll(
      operator: string,
      onBehalfOf: string,
      actionsBitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isBorrowAPRLowerThanLoanOfferAPRs(
      user: string,
      borrowAPR: BigNumberish,
      market: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isLoanAPRGreaterThanBorrowOfferAPRs(
      user: string,
      loanAPR: BigNumberish,
      market: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isMarket(candidate: string, overrides?: CallOverrides): Promise<boolean>;

    multicall(data: BytesLike[], overrides?: CallOverrides): Promise<string[]>;

    nonTransferrableTokenVaultImplementation(
      overrides?: CallOverrides
    ): Promise<string>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    removeMarket(market: string, overrides?: CallOverrides): Promise<void>;

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeAllAuthorizations(overrides?: CallOverrides): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAuthorization(
      operator: string,
      actionsBitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setCollectionsManager(
      _collectionsManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setNonTransferrableRebasingTokenVaultImplementation(
      _nonTransferrableTokenVaultImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSizeImplementation(
      _sizeImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setUserCollectionCopyLimitOrderConfigs(
      collectionId: BigNumberish,
      copyLoanOfferConfig: CopyLimitOrderConfigStruct,
      copyBorrowOfferConfig: CopyLimitOrderConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setUserCollectionCopyLimitOrderConfigsOnBehalfOf(
      collectionId: BigNumberish,
      copyLoanOfferConfig: CopyLimitOrderConfigStruct,
      copyBorrowOfferConfig: CopyLimitOrderConfigStruct,
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sizeImplementation(overrides?: CallOverrides): Promise<string>;

    subscribeToCollections(
      collectionIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    subscribeToCollectionsOnBehalfOf(
      collectionIds: BigNumberish[],
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    unsubscribeFromCollections(
      collectionIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    unsubscribeFromCollectionsOnBehalfOf(
      collectionIds: BigNumberish[],
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CollectionsManagerSet(address,address)"(
      oldCollectionsManager?: string | null,
      newCollectionsManager?: string | null
    ): CollectionsManagerSetEventFilter;
    CollectionsManagerSet(
      oldCollectionsManager?: string | null,
      newCollectionsManager?: string | null
    ): CollectionsManagerSetEventFilter;

    "CreateBorrowTokenVault(address)"(
      borrowTokenVault?: string | null
    ): CreateBorrowTokenVaultEventFilter;
    CreateBorrowTokenVault(
      borrowTokenVault?: string | null
    ): CreateBorrowTokenVaultEventFilter;

    "CreateMarket(address)"(market?: string | null): CreateMarketEventFilter;
    CreateMarket(market?: string | null): CreateMarketEventFilter;

    "CreatePriceFeed(address)"(
      priceFeed?: string | null
    ): CreatePriceFeedEventFilter;
    CreatePriceFeed(priceFeed?: string | null): CreatePriceFeedEventFilter;

    "Initialized(uint64)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "NonTransferrableRebasingTokenVaultImplementationSet(address,address)"(
      oldNonTransferrableRebasingTokenVaultImplementation?: string | null,
      newNonTransferrableRebasingTokenVaultImplementation?: string | null
    ): NonTransferrableRebasingTokenVaultImplementationSetEventFilter;
    NonTransferrableRebasingTokenVaultImplementationSet(
      oldNonTransferrableRebasingTokenVaultImplementation?: string | null,
      newNonTransferrableRebasingTokenVaultImplementation?: string | null
    ): NonTransferrableRebasingTokenVaultImplementationSetEventFilter;

    "RemoveMarket(address)"(market?: string | null): RemoveMarketEventFilter;
    RemoveMarket(market?: string | null): RemoveMarketEventFilter;

    "RevokeAllAuthorizations(address)"(
      sender?: string | null
    ): RevokeAllAuthorizationsEventFilter;
    RevokeAllAuthorizations(
      sender?: string | null
    ): RevokeAllAuthorizationsEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;

    "SetAuthorization(address,address,uint256,uint256)"(
      sender?: string | null,
      operator?: string | null,
      actionsBitmap?: BigNumberish | null,
      nonce?: null
    ): SetAuthorizationEventFilter;
    SetAuthorization(
      sender?: string | null,
      operator?: string | null,
      actionsBitmap?: BigNumberish | null,
      nonce?: null
    ): SetAuthorizationEventFilter;

    "SizeImplementationSet(address,address)"(
      oldSizeImplementation?: string | null,
      newSizeImplementation?: string | null
    ): SizeImplementationSetEventFilter;
    SizeImplementationSet(
      oldSizeImplementation?: string | null,
      newSizeImplementation?: string | null
    ): SizeImplementationSetEventFilter;

    "Upgraded(address)"(implementation?: string | null): UpgradedEventFilter;
    Upgraded(implementation?: string | null): UpgradedEventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    authorizationNonces(
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    authorizations(
      nonce: BigNumberish,
      operator: string,
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    callMarket(
      market: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    collectionsManager(overrides?: CallOverrides): Promise<BigNumber>;

    createBorrowTokenVault(
      variablePool: string,
      underlyingBorrowToken: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    createMarket(
      feeConfigParams: InitializeFeeConfigParamsStruct,
      riskConfigParams: InitializeRiskConfigParamsStruct,
      oracleParams: InitializeOracleParamsStruct,
      dataParams: InitializeDataParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    createPriceFeed(
      _priceFeedParams: PriceFeedParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getBorrowOfferAPR(
      user: string,
      collectionId: BigNumberish,
      market: string,
      rateProvider: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLoanOfferAPR(
      user: string,
      collectionId: BigNumberish,
      market: string,
      rateProvider: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarket(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketDescriptions(overrides?: CallOverrides): Promise<BigNumber>;

    getMarkets(overrides?: CallOverrides): Promise<BigNumber>;

    getMarketsCount(overrides?: CallOverrides): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _owner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    isAuthorized(
      operator: string,
      onBehalfOf: string,
      action: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAuthorizedAll(
      operator: string,
      onBehalfOf: string,
      actionsBitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isBorrowAPRLowerThanLoanOfferAPRs(
      user: string,
      borrowAPR: BigNumberish,
      market: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isLoanAPRGreaterThanBorrowOfferAPRs(
      user: string,
      loanAPR: BigNumberish,
      market: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isMarket(candidate: string, overrides?: CallOverrides): Promise<BigNumber>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    nonTransferrableTokenVaultImplementation(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    removeMarket(
      market: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    revokeAllAuthorizations(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setAuthorization(
      operator: string,
      actionsBitmap: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setCollectionsManager(
      _collectionsManager: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setNonTransferrableRebasingTokenVaultImplementation(
      _nonTransferrableTokenVaultImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setSizeImplementation(
      _sizeImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setUserCollectionCopyLimitOrderConfigs(
      collectionId: BigNumberish,
      copyLoanOfferConfig: CopyLimitOrderConfigStruct,
      copyBorrowOfferConfig: CopyLimitOrderConfigStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setUserCollectionCopyLimitOrderConfigsOnBehalfOf(
      collectionId: BigNumberish,
      copyLoanOfferConfig: CopyLimitOrderConfigStruct,
      copyBorrowOfferConfig: CopyLimitOrderConfigStruct,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    sizeImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    subscribeToCollections(
      collectionIds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    subscribeToCollectionsOnBehalfOf(
      collectionIds: BigNumberish[],
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unsubscribeFromCollections(
      collectionIds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    unsubscribeFromCollectionsOnBehalfOf(
      collectionIds: BigNumberish[],
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UPGRADE_INTERFACE_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    authorizationNonces(
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    authorizations(
      nonce: BigNumberish,
      operator: string,
      onBehalfOf: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    callMarket(
      market: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    collectionsManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createBorrowTokenVault(
      variablePool: string,
      underlyingBorrowToken: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    createMarket(
      feeConfigParams: InitializeFeeConfigParamsStruct,
      riskConfigParams: InitializeRiskConfigParamsStruct,
      oracleParams: InitializeOracleParamsStruct,
      dataParams: InitializeDataParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    createPriceFeed(
      _priceFeedParams: PriceFeedParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getBorrowOfferAPR(
      user: string,
      collectionId: BigNumberish,
      market: string,
      rateProvider: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLoanOfferAPR(
      user: string,
      collectionId: BigNumberish,
      market: string,
      rateProvider: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarket(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketDescriptions(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarkets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMarketsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _owner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isAuthorized(
      operator: string,
      onBehalfOf: string,
      action: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAuthorizedAll(
      operator: string,
      onBehalfOf: string,
      actionsBitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isBorrowAPRLowerThanLoanOfferAPRs(
      user: string,
      borrowAPR: BigNumberish,
      market: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isLoanAPRGreaterThanBorrowOfferAPRs(
      user: string,
      loanAPR: BigNumberish,
      market: string,
      maturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMarket(
      candidate: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multicall(
      data: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    nonTransferrableTokenVaultImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeMarket(
      market: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    revokeAllAuthorizations(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setAuthorization(
      operator: string,
      actionsBitmap: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setCollectionsManager(
      _collectionsManager: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setNonTransferrableRebasingTokenVaultImplementation(
      _nonTransferrableTokenVaultImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setSizeImplementation(
      _sizeImplementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setUserCollectionCopyLimitOrderConfigs(
      collectionId: BigNumberish,
      copyLoanOfferConfig: CopyLimitOrderConfigStruct,
      copyBorrowOfferConfig: CopyLimitOrderConfigStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setUserCollectionCopyLimitOrderConfigsOnBehalfOf(
      collectionId: BigNumberish,
      copyLoanOfferConfig: CopyLimitOrderConfigStruct,
      copyBorrowOfferConfig: CopyLimitOrderConfigStruct,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    sizeImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    subscribeToCollections(
      collectionIds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    subscribeToCollectionsOnBehalfOf(
      collectionIds: BigNumberish[],
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unsubscribeFromCollections(
      collectionIds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    unsubscribeFromCollectionsOnBehalfOf(
      collectionIds: BigNumberish[],
      onBehalfOf: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
